version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: esnfm
      POSTGRES_PASSWORD: esnfm_dev
      POSTGRES_DB: esnfm
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: